// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    data_coalition
    (
        init => init
        upgrade => upgrade
        create => create_endpoint
        grantAccess => grant_access_endpoint
        revokeAccess => revoke_access_endpoint
        addAdmin => add_admin_endpoint
        removeAdmin => remove_admin_endpoint
        getAdmins => admins
        initDaoModule => init_dao_module_endpoint
        getDaoVoteWeight => get_dao_vote_weight_view
        getDaoMembers => get_dao_members_view
        initAggregateModule => init_aggregate_module_endpoint
        addCategory => add_category_endpoint
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
