// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           24
// Async Callback:                       1
// Total number of exported functions:  26

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    data_coalition
    (
        init => init
        upgrade => upgrade
        create => create_endpoint
        grantAccess => grant_access_endpoint
        revokeAccess => revoke_access_endpoint
        getInfo => get_info_view
        initConfigModule => init_config_module_endpoint
        addAdmin => add_admin_endpoint
        removeAdmin => remove_admin_endpoint
        getAdmins => admins
        getDaoWeight => delegations_amount
        initDaoModule => init_dao_module_endpoint
        getDaoVoteWeight => get_dao_vote_weight_view
        getDaoMembers => get_dao_members_view
        initAggregateModule => init_aggregate_module_endpoint
        addCategory => add_category_endpoint
        removeCategory => remove_category_endpoint
        setBoardMinStake => set_board_min_stake_endpoint
        setBoardMinStakeDuration => set_board_min_stake_duration_endpoint
        acceptBoardMember => accept_board_member_endpoint
        unlockBoardMember => unlock_board_member_endpoint
        stake => stake_endpoint
        unstake => unstake_endpoint
        getStakeUnlockTime => stake_unlock_time
        getStakeLockTimeSeconds => stake_lock_time_seconds
    )
}

multiversx_sc_wasm_adapter::async_callback! { data_coalition }
